name: 'Ruby pronto Action'
description: 'Pronto for Ruby'
author: 'ajapon88'
inputs:
  commit:
    description: 'Commit for the diff.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - run
    - -f
    - github_pr_review
    - github_pr
    - -c
    - ${{ inputs.commit }}
