# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "pronto", "~> 0.10.0"
gem "pronto-rubocop",        require: false
gem "rubocop",               require: false
gem "rubocop-performance",   require: false
gem "rubocop-rspec",         require: false
gem "rubocop-rspec-focused", require: false
gem "rubocop-rake",          require: false
gem "rubocop-rails",         require: false
