name: 'Pronto Ruby Action'
description: 'Pronto for Ruby'
author: 'ajapon88'
inputs:
  formatters:
    description: 'Pick output formatters.'
    required: true
    default: >-
      github_pr_review
      github_pr
  commit:
    description: 'Commit for the diff.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.formatters }}
    - ${{ inputs.commit }}
